// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: health/v1/service.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on ReadyRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ReadyRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ReadyRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ReadyRequestMultiError, or
// nil if none found.
func (m *ReadyRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ReadyRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return ReadyRequestMultiError(errors)
	}

	return nil
}

// ReadyRequestMultiError is an error wrapping multiple validation errors
// returned by ReadyRequest.ValidateAll() if the designated constraints aren't met.
type ReadyRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ReadyRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ReadyRequestMultiError) AllErrors() []error { return m }

// ReadyRequestValidationError is the validation error returned by
// ReadyRequest.Validate if the designated constraints aren't met.
type ReadyRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ReadyRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ReadyRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ReadyRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ReadyRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ReadyRequestValidationError) ErrorName() string { return "ReadyRequestValidationError" }

// Error satisfies the builtin error interface
func (e ReadyRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sReadyRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ReadyRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ReadyRequestValidationError{}

// Validate checks the field values on ReadyResponse with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ReadyResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ReadyResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ReadyResponseMultiError, or
// nil if none found.
func (m *ReadyResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ReadyResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return ReadyResponseMultiError(errors)
	}

	return nil
}

// ReadyResponseMultiError is an error wrapping multiple validation errors
// returned by ReadyResponse.ValidateAll() if the designated constraints
// aren't met.
type ReadyResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ReadyResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ReadyResponseMultiError) AllErrors() []error { return m }

// ReadyResponseValidationError is the validation error returned by
// ReadyResponse.Validate if the designated constraints aren't met.
type ReadyResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ReadyResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ReadyResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ReadyResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ReadyResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ReadyResponseValidationError) ErrorName() string { return "ReadyResponseValidationError" }

// Error satisfies the builtin error interface
func (e ReadyResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sReadyResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ReadyResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ReadyResponseValidationError{}
